### ISSUE TITLE
Wai you no fully remove the most basic version of Arxan?!one!  

### ISSUE THREAD

**Issue by Convery** [IW4x/iw6x-client#1]
:3

**Comment by momo5502** [comment]
Hehe, I'm on it 😬

**Comment by momo5502** [comment]
Even if arxan is still not fully unpatched, it's unpatched in a state that is sufficient for further progress.
I was outsmarted by the un-smartness of arxan.

In fact it doesn't have integrity checks, it simply unpacks the binary. And that in multiple steps.

A hook that allows to interact with the game after the binary is fully unpacked is totally sufficient for now.
In the future it might make sense if we do the unpacking manually to have better control over what's going on, but that's not necessary for further development.

Using the post_unpack() interface for modules allows to manipulate the game in every way possible.
For reverse engineering I recommend renaming the .reloc section (to for example .arxan), as IDA will falsely leave out that section from the analysis process.

I won't close that issue yet, but it's definitely not important anymore.

**Comment by momo5502** [comment]
As hinted by @aerosoul94 the option PE_LOAD_ALLSECTIONS can be enabled in IDA's cfg/pe.cfg to force loading all sections, instead of renaming the .reloc section.

**Comment by momo5502** [comment]
Actually, this can be closed. If need for further patches arises, a new issue can be created.
