### ISSUE TITLE
Vsync 15FPS bug

### ISSUE THREAD

**Issue by FritasTechTips** [IW4x/iw6x-client#22]
Needs further testing on 60hz monitor users. This didn't seem to happen until I test out "Add required demonware services for matchmaking" commit. My FPS locked to 15 and after I tried the before commits it seem to be still broken which is VERY odd as I never run up to this issue 

On steam IW6. I never run up to this issue at all. 

The solution I found is to to toggle r_vsync (0 and 1) in the console and not touch the menu. Never touched com_maxfps. Tested to 2 PC's so far with the same issue. Not sure if it did something to my players2 cfg or what. I will do a deep investigation to this issue when I have time. If anybody else couldn't figure it out.

**Comment by momo5502** [comment]
This is probably related to 4177c1ab9eeb3d56ca2a8e95e3fa627201e52f19
You can try deleting your config/players2 folder and test before that commit.
