### ISSUE TITLE
Changing password in private match crashes

### ISSUE THREAD

**Issue by skiff** [IW4x/iw6x-client#80]
If you load up a private match, click game setup and try to change the password your game will crash. From what I can tell it looks like it is caused by something on steam not being emulated but I'm really not 100% sure

**Comment by OneFourOne** [comment]
Just tested this, I don't seem to crash
I Clicked Private match --> Game Setup --> Changed Password --> Started Match
This is what you're doing right?

**Comment by skiff** [comment]
Yeah that's what I was doing. I have no idea what changed but this morning its no longer crashing for me. I must have been missing some recent commits when I wrote this up but I will close it now.
